// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzVrzPXyqwXN5TFevMqWY-eOz58f3Zb3k',
    appId: '1:336545282851:web:73ae3ecc3ab98a87eb2a96',
    messagingSenderId: '336545282851',
    projectId: 'spaza-4a28b',
    authDomain: 'spaza-4a28b.firebaseapp.com',
    storageBucket: 'spaza-4a28b.appspot.com',
    measurementId: 'G-XMZ6C43GT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjqHEsdXcu0s7VV_x9-BpQDd4skDE3NCc',
    appId: '1:336545282851:android:d2f898902e85ad75eb2a96',
    messagingSenderId: '336545282851',
    projectId: 'spaza-4a28b',
    storageBucket: 'spaza-4a28b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMFCR83xpaqW_yS0tfSjrtz_vclCVjvPk',
    appId: '1:336545282851:ios:2d947b0691712928eb2a96',
    messagingSenderId: '336545282851',
    projectId: 'spaza-4a28b',
    storageBucket: 'spaza-4a28b.appspot.com',
    iosBundleId: 'app.web.amstyles.spaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMFCR83xpaqW_yS0tfSjrtz_vclCVjvPk',
    appId: '1:336545282851:ios:38a4b31402fe90f6eb2a96',
    messagingSenderId: '336545282851',
    projectId: 'spaza-4a28b',
    storageBucket: 'spaza-4a28b.appspot.com',
    iosBundleId: 'app.web.amstyles.spaza.RunnerTests',
  );
}
